homeassistant:
  name: Home
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  elevation: 100
  unit_system: metric
  time_zone: Europe/Moscow
  customize: !include include/customize.yaml
  packages: !include_dir_named ./include/integrations/

config:
frontend:
history:
logbook:

# mobile_app for mobile app work. New feature in dec 2019 
mobile_app:

# person: Новое в 0.88 появилось
sun:
# System Health integration data can be viewed in Developer Tools on the “Info” tab
system_health:
zeroconf:
  
# I use mariadb on host machine
recorder:
  db_url: !secret recorder_db_url

http:
  base_url: !secret my_base_url
  ip_ban_enabled: true

discovery:
  ignore:
    - yeelight

################################################
##         Includes                           ##
################################################
automation: !include_dir_merge_list include/automations/
script: !include_dir_merge_named include/scripts/
scene: !include_dir_merge_list include/scenes/
group: !include include/groups.yaml
yeelight: !include include/yeelight.yaml
tts: !include include/tts.yaml
timer: !include include/timers.yaml
vacuum: !include include/vacuum.yaml

cast:
  media_player:
    - host: !secret google_home_mini_ip


# telegram_bot:
#   - platform: polling
#     api_key: !secret telegram_bot_api_key
#     proxy_url: !secret proxy_socks5_url
#     proxy_params:
#       username: !secret proxy_socks5_name
#       password: !secret proxy_socks5_pass
#     allowed_chat_ids:
#       - !secret telegrma_bot_allowed_chat_id1
#       - !secret telegrma_bot_allowed_chat_id2

    # standby_connection: true
  # customize:
  #   sources:
  #     - livetv
  #     - youtube
  #     - makotv
  #     - netflix

media_player:
# notify:
# notify:
#   - name: telegram
#     platform: telegram
#     chat_id: !secret telegrma_bot_allowed_chat_id1

