- alias: "Dracena - time to water"
  trigger:
    - platform: time
      at: "20:00:00"
  condition:
    condition: numeric_state 
    entity_id: sensor.dracena_moister
    below: 5
  action:
    - service: tts.yandextts_say
      entity_id: media_player.googlehomemini
      data:
        message: "Полей пожалуйста Драценочку, приятель."