- alias: "Auto turn on server plug"
  trigger:
    platform: state
    entity_id: switch.xiaomi_switch_1
    # from: on 
    to: 'off' 
    for: "00:01:00"
  action:
    - service: switch.turn_on
      entity_id: switch.xiaomi_switch_1
    - service: notify.telegram_notifier
      data:
        message: "В доме включили электричество. Включаю резервную линию к основному электропитанию"
- alias: "No power in house"
  trigger:
    platform: state
    entity_id: binary_sensor.google_home_mini_ping
    from: 'on'
    to: 'off'
  action:
    - service: notify.telegram_notifier
      data:
        message: "В доме отключили электричество"