binary_sensor:
  - platform: ping
    name: Server in France
    host: !secret server_in_france_ip
    count: 3
    scan_interval: 900
  - platform: ping
    name: Core i5 server
    host: !secret server_i5_ip
    count: 3
    scan_interval: 900
  - platform: ping
    name: google_home_mini_ping 
    host: !secret google_home_mini_ip
    count: 3
    scan_interval: 60
  - platform: tod
    name: night_time
    after: '20:00'
    before: '06:00'
  - platform: template
    sensors:
      fridge_late_night_binge_eating:
        friendly_name: "Ночной жор"
        value_template: >
          {{ is_state("binary_sensor.night_time", "on") 
          and is_state("binary_sensor.temp_door_sensor_aqara", "on") }}